### PR TITLE
slides/inria-academy

### PR DESCRIPTION
**Pull request by fjmolinas**
Initial draft for Inria-academy slides, next we would follow the regular course start with the introduction slides. I might still updated the agenda.

### CODE REVIEW

**Comment by aabadie** [comment]
Have you checked https://github.com/RIOT-OS/riot-course/tree/master/slides/tutorial-inria-academy ?

**Comment by fjmolinas** [comment]
Yes but I saw that it was basically Introduction, so instead I went for modifying the introduction slides and just adding a prelude.

**Comment by fjmolinas** [comment]
> Yes but I saw that it was basically Introduction, so instead I went for modifying the introduction slides and just adding a prelude.

So what I wanted to avoid was multiple slides with exactly the same content, and It looked like the Inria-Academy slides were exactly the same as the introduction... so I wanted to avoid duplication but sure I guess I can reuse that.

**Comment by fjmolinas** [comment]
> > Yes but I saw that it was basically Introduction, so instead I went for modifying the introduction slides and just adding a prelude.
> 
> So what I wanted to avoid was multiple slides with exactly the same content, and It looked like the Inria-Academy slides were exactly the same as the introduction... so I wanted to avoid duplication but sure I guess I can reuse that.

Should I patch the existing slides then?

**Comment by fjmolinas** [comment]
Did as suggested, Now it just adds some introductory slides and aligns with changes in introduction

**Pull request merged**
